version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
